<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KaryawanSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $data = [
            ['nip' => 'LMG-2015-001', 'nama' => 'ANIK', 'bagian' => 'TL Cuci', 'barcode_value' => 'LMG-2015-001', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-003', 'nama' => 'ST. NUR FAROKAH', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2015-003', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-005', 'nama' => 'SRI UTAMI', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2015-005', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-008', 'nama' => 'SITI NUR FADLIHA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2015-008', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-012', 'nama' => 'YULIATIN', 'bagian' => 'SPV Moulding', 'barcode_value' => 'LMG-2015-012', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-014', 'nama' => 'ANITA', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2015-014', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2015-015', 'nama' => 'KARYAWATI', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2015-015', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2016-016', 'nama' => 'NURKHASANAH', 'bagian' => 'GTL Moulding', 'barcode_value' => 'LMG-2016-016', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2016-019', 'nama' => 'TUTIK', 'bagian' => 'GTL Cabut', 'barcode_value' => 'LMG-2016-019', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2016-020', 'nama' => 'SURAT', 'bagian' => 'Driver', 'barcode_value' => 'LMG-2016-020', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2016-022', 'nama' => 'SRI SUNARTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2016-022', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-023', 'nama' => 'EVI ANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2017-023', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-028', 'nama' => 'SULAIKAH', 'bagian' => 'SPV Kedatangan', 'barcode_value' => 'LMG-2017-028', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-030', 'nama' => 'SUWANTO', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2017-030', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-032', 'nama' => 'ULUL KHOIRIAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2017-032', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-034', 'nama' => 'SUWANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2017-034', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-001', 'nama' => 'DIAN NOVITA ROSIDA', 'bagian' => 'Admin Produktivitas', 'barcode_value' => 'LMG-2018-001', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-038', 'nama' => 'JEKY ARIYANTO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2018-038', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-039', 'nama' => 'MUHAMMAD REGATANA', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2018-039', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-043', 'nama' => 'SITI ROMLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2018-043', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-047', 'nama' => 'FHILIS SULESTARI', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2018-047', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-049', 'nama' => 'ANAS JA\'FAR', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2018-049', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-053', 'nama' => 'SUPI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2018-053', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-061', 'nama' => 'UMAIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2018-061', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2019-064', 'nama' => 'DENIKO FERGIAN R', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2019-064', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-736', 'nama' => 'INDRI NUR ISNIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-736', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2019-069', 'nama' => 'INDAH PERMATA SARI', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2019-069', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2019-077', 'nama' => 'WAHYU SURODO', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2019-077', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2019-079', 'nama' => 'UMARIYAH', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2019-079', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-737', 'nama' => 'NIKEN PUPUT MELATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-737', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-735', 'nama' => 'SELVIANA MAYANGSARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-735', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2020-105', 'nama' => 'CANKISWAN', 'bagian' => 'TL Kedatangan', 'barcode_value' => 'LMG-2020-105', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2020-111', 'nama' => 'OQKY VERDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2020-111', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-126', 'nama' => 'DIMAS ADI PUTRA STIAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-126', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-176', 'nama' => 'DWI BAGUS SANTOSO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-176', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-129', 'nama' => 'NU\'MAN WA\'D PRAWIRO N.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-129', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-130', 'nama' => 'M.JAMALUDIN AKBAR', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2021-130', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-134', 'nama' => 'AGUS KURNIAWAN', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2021-134', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-136', 'nama' => 'SHELY ANGGRAINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-136', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-138', 'nama' => 'ROBBY ENDHY GABRIELEO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-138', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-751', 'nama' => 'SAIFUL GUNAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-751', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-147', 'nama' => 'ABDUL ROUF KHOIRI', 'bagian' => 'GTL Moulding', 'barcode_value' => 'LMG-2021-147', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-148', 'nama' => 'SHENDY NOPITA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-148', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-163', 'nama' => 'YESY WIDYAH KRISTANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-163', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-306', 'nama' => 'MUHAMMAD TAMAMUR RIDWAN', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2022-306', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-519', 'nama' => 'ETIKA AINUR ROHMAH', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2022-519', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-742', 'nama' => 'FENCI PERMATA FIRNA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-742', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-360', 'nama' => 'KOKO HANDOKO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-360', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-387', 'nama' => 'FEBRIANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-387', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-307', 'nama' => 'PUPUT INDRAWATI', 'bagian' => 'TL Pengiriman', 'barcode_value' => 'LMG-2022-307', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-181', 'nama' => 'AHMAD FUADDIN THOHARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-181', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-288', 'nama' => 'IMAM KHUSNUL', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-288', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-311', 'nama' => 'PRAYOGA DWI CAHYO', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2022-311', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-314', 'nama' => 'ISHAQ', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-314', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-358', 'nama' => 'TSALIS AKMALUDIN NI\'AM', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2022-358', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-419', 'nama' => 'RIO SARNUDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-419', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-436', 'nama' => 'NUR ALIM ZAINURI', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2022-436', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-455', 'nama' => 'NIKO YUDHO BINTORO', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2022-455', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-494', 'nama' => 'DANDI MAHA PUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-494', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-510', 'nama' => 'ALI MASKAN ,MUSA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-510', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-514', 'nama' => 'ERIAN AHMAD ANUGRAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-514', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-744', 'nama' => 'ANISA RIZQI MARZUQOH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-744', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-747', 'nama' => 'HANIFATUL NUR AINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-747', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-746', 'nama' => 'ANAS SOFI QONIT TATILAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-746', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-319', 'nama' => 'YULIANA DWI ROCHMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-319', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-389', 'nama' => 'RINTO BINARKO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-389', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-484', 'nama' => 'YAYUK EKOWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-484', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-487', 'nama' => 'ANIS ANDARWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2022-487', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-745', 'nama' => 'EKA NAYLA QAIRANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-745', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2020-114', 'nama' => 'NURIYATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2020-114', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-863', 'nama' => 'YOFI ANDREYAN MAULANA', 'bagian' => 'Security', 'barcode_value' => 'LMG-2024-863', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-866', 'nama' => 'MUHAMMAD AFANDI', 'bagian' => 'Security', 'barcode_value' => 'LMG-2024-866', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1005', 'nama' => 'M. GAUNG SIDIQ ALFAINI', 'bagian' => 'TL Cutter & Flek', 'barcode_value' => 'LMG-2024-1005', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1006', 'nama' => 'NILA WIDIA SARI', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2024-1006', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-238', 'nama' => 'DANY WAHYU HUDISMAWAN', 'bagian' => 'Superintenden', 'barcode_value' => 'LMG-2025-238', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-881', 'nama' => 'ANDREAN FELANI', 'bagian' => 'Security', 'barcode_value' => 'LMG-2024-881', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-902', 'nama' => 'NUR ARROFATUL FITRIYAH', 'bagian' => 'Security', 'barcode_value' => 'LMG-2024-902', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1003', 'nama' => 'SAFRIDAHANI', 'bagian' => 'Superintenden', 'barcode_value' => 'LMG-2024-1003', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-974', 'nama' => 'KHUSNUL FATIMAH', 'bagian' => 'Payroll', 'barcode_value' => 'LMG-2024-974', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-236', 'nama' => 'Ahmad Maulana Iskhaq', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-236', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2017-035', 'nama' => 'RULIATUL FIDIAH', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2017-035', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-272', 'nama' => 'RISKA OKTAVIANA', 'bagian' => 'Security', 'barcode_value' => 'LMG-2025-272', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-139', 'nama' => 'AHMAD NURUL IZZUDDIN', 'bagian' => 'TL Moulding', 'barcode_value' => 'LMG-2021-139', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-282', 'nama' => 'M. ANAS FABIAN TORO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-282', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2022-454', 'nama' => 'YUNI INDARWATI', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2022-454', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-751', 'nama' => 'RAIHAN RANGGA ANDHIKA P', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2023-751', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-569', 'nama' => 'KERINNA', 'bagian' => 'GTL Packing', 'barcode_value' => 'LMG-2023-569', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-016', 'nama' => 'ZUSITA ARDHIA INDRAYANI', 'bagian' => 'TL Cabut', 'barcode_value' => 'LMG-2023-016', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-321', 'nama' => 'KIDUNG ALFIANI SIDIQ', 'bagian' => 'HRD', 'barcode_value' => 'LMG-2024-321', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-579', 'nama' => 'TONI IKHWANDI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-579', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-589', 'nama' => 'ANGGI ALFRIADIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-589', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-649', 'nama' => 'MOH. FIRDAN ADDY M.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-649', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-670', 'nama' => 'DEDIK PRASTYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-670', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-702', 'nama' => 'MUHAMMAD DAFIN WIDYANTO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-702', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-707', 'nama' => 'MUHAMMAD CHAKIMUN ALIM', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-707', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-738', 'nama' => 'RIA SETYO WATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-738', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-731', 'nama' => 'MAINDRA ANDRI PRANATA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-731', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-756', 'nama' => 'M. ZAINUL MU\'ARIF', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-756', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-758', 'nama' => 'HENDRIK WIJAYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-758', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-772', 'nama' => 'ANISA INDAH PERMATA S', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-772', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-773', 'nama' => 'FAHMI MAULANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-773', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-775', 'nama' => 'M. JAMALUDDIN SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-775', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-793', 'nama' => 'FARID JUNAIDI PRASTYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-793', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-192', 'nama' => 'M. NURUL YAQHIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-192', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-143', 'nama' => 'RATNA SUMINAR', 'bagian' => 'Finance Accounting', 'barcode_value' => 'LMG-2025-143', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-243', 'nama' => 'AHMAD NUR SHOLIHUDIN D', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-243', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-244', 'nama' => 'MOKHAMAD ILHAM MATINU J', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-244', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-245', 'nama' => 'ANDRI SETIAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-245', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-151', 'nama' => 'NAJWA PUTRI SALSABILLAH', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2025-151', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-247', 'nama' => 'M. FAIS FEBRIAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-247', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-149', 'nama' => 'Iis Purwanti', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-149', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-150', 'nama' => 'AGUSTINA AULIANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-150', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-041', 'nama' => 'FATKHOR ROHMAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-041', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1022', 'nama' => 'ANDRE FEBIAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1022', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-874', 'nama' => 'AHMAD SURURI', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-874', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1050', 'nama' => 'SUWARI', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-1050', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1039', 'nama' => 'SUHAR', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-1039', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-232', 'nama' => 'SUKAMTO', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-232', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-277', 'nama' => 'UJENG NOVIANA', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-277', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-309', 'nama' => 'SITI JAMIL RATNAWATI', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2024-309', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-530', 'nama' => 'SUTIKA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-530', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-455', 'nama' => 'PANJI DWI ARDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-455', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-556', 'nama' => 'TOTOK PRASETYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-556', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-777', 'nama' => 'JUMASRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-777', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-289', 'nama' => 'YUNANDA NUR P', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-289', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-537', 'nama' => 'MUKAMAD KURNIAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-537', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-547', 'nama' => 'ATMA DWI YULIKUSTANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-547', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2018-054', 'nama' => 'KHALAWATUL IMAH', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2018-054', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-947', 'nama' => 'RAHMATUS SIAMI ZULFIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-947', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1009', 'nama' => 'NURUL ALFIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1009', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-153', 'nama' => 'LUSI FEBIYANTI NUR S', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-153', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-214', 'nama' => 'WULAN OKTAVIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-214', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-247', 'nama' => 'JULIANA NUR AFRIZA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-247', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-219', 'nama' => 'M. ALFIAN RUDI ISWANTO', 'bagian' => 'Maintenance', 'barcode_value' => 'LMG-2024-219', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-229', 'nama' => 'SYAF\'ATUN MUAWANAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-229', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-230', 'nama' => 'TRI ULAN IRNAWATI', 'bagian' => 'GTL Packing', 'barcode_value' => 'LMG-2024-230', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-158', 'nama' => 'NOVA GITA LINDA SAFITRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-158', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-156', 'nama' => 'FAIZAH ERKA MAYLANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-156', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-157', 'nama' => 'NABILA EKA MARSYA A', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-157', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-308', 'nama' => 'DEWI SAGITA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-308', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-327', 'nama' => 'LILIS NUR QOMARIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-327', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-550', 'nama' => 'MOCHAMMAD TAMAM A.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-550', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-580', 'nama' => 'MUHAMAD NAFIS ABDILLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-580', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-622', 'nama' => 'SRI MULYATI NINGSIH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-622', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-623', 'nama' => 'ASMAIYA', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2023-623', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-635', 'nama' => 'SULISTIYOWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-635', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2023-807', 'nama' => 'AINUL YAKIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2023-807', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-819', 'nama' => 'YUDHISTIRA PUJI UTOMO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-819', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-825', 'nama' => 'CANDRA WAHYU ERIESANDO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-825', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-862', 'nama' => 'SUNARSIH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-862', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-885', 'nama' => 'SETIA SUDARMO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-885', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-901', 'nama' => 'ROSLIANA SALSA R', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-901', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-914', 'nama' => 'MIFTAKHUR RAMADHAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-914', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-915', 'nama' => 'NITA NURUL AINI', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2024-915', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-250', 'nama' => 'NIKO ARIA SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-250', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-941', 'nama' => 'JOKO JATMIKO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-941', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-948', 'nama' => 'DIYON PRATAMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-948', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-952', 'nama' => 'IAN ADHQON MAULANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-952', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-959', 'nama' => 'AKUWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-959', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1016', 'nama' => 'SALSA DINA SAFITRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1016', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1036', 'nama' => 'ANDIKA PUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1036', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1046', 'nama' => 'MUH RAMDHANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1046', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1063', 'nama' => 'AGUNG SAIFUDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1063', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1065', 'nama' => 'EMANUAL ARVIT AFRIZA', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2024-1065', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1072', 'nama' => 'MASFUFAH ARIANI PUTRI Y', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1072', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1079', 'nama' => 'NUR HIDAYATUS SOFIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1079', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1080', 'nama' => 'KHOLIFATUL NINDI PUTRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1080', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1087', 'nama' => 'MOHAMMAD JOFAN ENFARAMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1087', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1093', 'nama' => 'AHMAD FA\'IZ KURNAIDI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1093', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1098', 'nama' => 'SATRIA RAHMAD NOVIAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1098', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-107', 'nama' => 'IKRIMATUL WAHYUNI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-107', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-113', 'nama' => 'NEZA MEI AZZAHRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-113', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-124', 'nama' => 'USWATUN KHASANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-124', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-131', 'nama' => 'ZULIYATIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-131', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-135', 'nama' => 'NINIK NURYATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-135', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-136', 'nama' => 'DIVA NELI AGUSTIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-136', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-137', 'nama' => 'ELI ERNAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-137', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-141', 'nama' => 'SRI HANDAYANI F', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-141', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-213', 'nama' => 'Vionanda', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-213', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-151', 'nama' => 'ENDANG SETIYOWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-151', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-156', 'nama' => 'AHMAD SUHARTONO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-156', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-158', 'nama' => 'WIDYA TANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-158', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-165', 'nama' => 'SRI HANDAYANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-165', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-168', 'nama' => 'IRMA NURAINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-168', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-170', 'nama' => 'ALVI MAQNAULIA A.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-170', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-173', 'nama' => 'ADI FIRNANDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-173', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-184', 'nama' => 'EKO REONALD DOLINGGA P.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-184', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-190', 'nama' => 'ANDRIAN AJI PRATAMA', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2024-190', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-198', 'nama' => 'NIA NOFITA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-198', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-224', 'nama' => 'AGUNG HERMANSAH', 'bagian' => 'Checker Cabut', 'barcode_value' => 'LMG-2024-224', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-235', 'nama' => 'JOKO MAULANA P.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-235', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-238', 'nama' => 'DESVITA RAHAYU R.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-238', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-278', 'nama' => 'AHMAD MISBAHUDDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-278', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-280', 'nama' => 'HERFANDA FEBRIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-280', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-287', 'nama' => 'GANDA DONI DANAWA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-287', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-257', 'nama' => 'INDRA AGUNG R.', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-257', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-311', 'nama' => 'LITA WAHYUNI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-311', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-313', 'nama' => 'AGUS PRASETYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-313', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-332', 'nama' => 'RIFFA MUSTIKA ZAEN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-332', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-335', 'nama' => 'ARTHAMEVIA DWI F', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-335', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2021-122', 'nama' => 'SUHARTINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2021-122', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-337', 'nama' => 'A AMBAR WATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-337', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-256', 'nama' => 'NALINDRA ADITYA SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-256', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-280', 'nama' => 'AHMAD ABDUL SAFARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-280', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-371', 'nama' => 'M. RIZA ARMADANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-371', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-285', 'nama' => 'NILAL AMANI FITRIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-285', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-284', 'nama' => 'FITRI ERA FAZIRAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-284', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-068', 'nama' => 'DESIANA NUR AZIZAH', 'bagian' => 'Purchasing/ Logistic', 'barcode_value' => 'LMG-2025-068', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-030', 'nama' => 'MARGARETHA BICI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-030', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-044', 'nama' => 'FAROH AFIFUDIN M', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-044', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-016', 'nama' => 'FARENGGA KIKO RONALSA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-016', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-097', 'nama' => 'SITI NURAISAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-097', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-064', 'nama' => 'RADIT SETIA YOGA P', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-064', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-065', 'nama' => 'RIA SEPTI ARINDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-065', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-078', 'nama' => 'FATIMAH MUDAIM', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-078', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-082', 'nama' => 'SEFRIAN YANUAR K', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-082', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-084', 'nama' => 'ACHMAD ROFIQ M', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-084', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-772', 'nama' => 'NADIYATUL MA\'RIFAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-772', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-087', 'nama' => 'NANDA FINATA NUR R', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-087', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-089', 'nama' => 'ANANDIYATUL K', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-089', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-103', 'nama' => 'ACHMAD PRIMA RIZKI R', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-103', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-104', 'nama' => 'A REZA FALEFI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-104', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2024-1099', 'nama' => 'HANIM ZURIDIS ISTIQOMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2024-1099', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-112', 'nama' => 'Diwanto', 'bagian' => 'Maintenance', 'barcode_value' => 'LMG-2025-112', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-136', 'nama' => 'HAPPY MASLUKHA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-136', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-140', 'nama' => 'CINDY ARISTA W', 'bagian' => 'Security', 'barcode_value' => 'LMG-2025-140', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-179', 'nama' => 'DIKY ARDIANTO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-179', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-165', 'nama' => 'ZALFA DION ALIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-165', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-169', 'nama' => 'WANDA LEVIA AGUSTINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-169', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-215', 'nama' => 'ELVIAN CATUR WIJAYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-215', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-203', 'nama' => 'YULIANA SANTOSO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-203', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-204', 'nama' => 'YUNI INDAH PERTIWI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-204', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-206', 'nama' => 'Hernipurwaningsis', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-206', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-205', 'nama' => 'SRI WITDIATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-205', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-208', 'nama' => 'ADITYO EKA PRASETYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-208', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-209', 'nama' => 'DAFFA ISLAMIC SETYONO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-209', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-210', 'nama' => 'M RASSYA EIDI PRATAMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-210', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-212', 'nama' => 'Widia Fazira', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-212', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-192', 'nama' => 'REY RAFELA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-192', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-202', 'nama' => 'ASTUTIK', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-202', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-314', 'nama' => 'DIKI ARNANDO PRASTIO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-314', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-313', 'nama' => 'DWI DIPOWIYOSO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-313', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-309', 'nama' => 'DWI SINTA YULIANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-309', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-371', 'nama' => 'AHMAD SHOHAZAR', 'bagian' => 'IT Staff', 'barcode_value' => 'LMG-2025-371', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-383', 'nama' => 'Pramono', 'bagian' => 'Driver', 'barcode_value' => 'LMG-2025-383', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-453', 'nama' => 'NUR AINNIYAH SHOLIKHAH', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2025-453', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-357', 'nama' => 'RINI NUR AZIZA ARIANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-357', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-350', 'nama' => 'VINDI SALSA BELA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-350', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-425', 'nama' => 'M TEGUH FIRMASYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-425', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-424', 'nama' => 'ABDUL FATAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-424', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-431', 'nama' => 'NINDI FEBIANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-431', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-225', 'nama' => 'TAZKIA AULIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-225', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-365', 'nama' => 'KHOIRUL ABIDIN', 'bagian' => 'Admin', 'barcode_value' => 'LMG-2025-365', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-416', 'nama' => 'DWI FIDYA RATNASARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-416', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-406', 'nama' => 'KHUSNUL KHOIRIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-406', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-378', 'nama' => 'HENI NIDIA DWI AGUSTINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-378', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-379', 'nama' => 'AHMAD FAJAR SHODIQ', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-379', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-915', 'nama' => 'MIFTACHUL ASRORI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-915', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-421', 'nama' => 'AHMAD RIZKY', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-421', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-414', 'nama' => 'DIANA SILVIA DEWI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-414', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-347', 'nama' => 'M FARID AMIRUDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-347', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-356', 'nama' => 'INDARWATI BJ', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-356', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-429', 'nama' => 'SINTA FITRIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-429', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-363', 'nama' => 'KHOFIFATUS SA\'ADAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-363', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-423', 'nama' => 'AHMAD HIKMA KHOIRUL HUDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-423', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-372', 'nama' => 'RIANTIKA DWI JAYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-372', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-312', 'nama' => 'M ALIYUDIN SYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-312', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-303', 'nama' => 'Wilda', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-303', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-361', 'nama' => 'ANGGUN FEBRIYANTI ROHMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-361', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-319', 'nama' => 'MUCHAMMAD RIZKY FAJAR ROMANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-319', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-426', 'nama' => 'AHMAD ZAINUL AZHAR', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-426', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-444', 'nama' => 'IRVAN MAULANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-444', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-366', 'nama' => 'GILANG SATRIA NANDA P', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-366', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-451', 'nama' => 'LAILATUL FITRIA SHOLEHATUN NIKMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-451', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-435', 'nama' => 'ISVANDIANA ZAHROTUL JANNAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-435', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-393', 'nama' => 'OKTA AYU INDARWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-393', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-362', 'nama' => 'MARCELLA ANGGRAENI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-362', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-450', 'nama' => 'NUR AINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-450', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-446', 'nama' => 'ANNA AYUNDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-446', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-405', 'nama' => 'MIFTAHUS SHOLIHA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-405', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-385', 'nama' => 'NAZILATUR RAHMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-385', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-338', 'nama' => 'BAYU DUWIYUL ANGGARA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-338', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-302', 'nama' => 'APRILIA IVANAX', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-302', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-430', 'nama' => 'SA\'ADATUM MAHMUDAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-430', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-376', 'nama' => 'REVALDI DWI PRASETYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-376', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-339', 'nama' => 'WAHYU IMANUDIN HARIS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-339', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-457', 'nama' => 'FONI SELLA AYU NINGTIYAS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-457', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-466', 'nama' => 'NELLA DHEA MALINDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-466', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-459', 'nama' => 'SANDRA SINDIO WATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-459', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-458', 'nama' => 'NADILA AYU ALFIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-458', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-456', 'nama' => 'DWI RISKI AKBAR M', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-456', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-467', 'nama' => 'SITI KHUSNUL KOTIMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-467', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-461', 'nama' => 'M KEFIN AL HABIB', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-461', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-164', 'nama' => 'M WAHYU DAFFA RAMADAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-164', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-370', 'nama' => 'HAJAR SUNTORO', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2025-370', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-480', 'nama' => 'Fandhi ahmad', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-480', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-398', 'nama' => 'M rofiq aditya', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-398', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-399', 'nama' => 'Abdul manan', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-399', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-478', 'nama' => 'Afidatul kusmiati', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-478', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-475', 'nama' => 'Winda nurhidayah', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-475', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-499', 'nama' => 'SAFA\'ATI ARODNA ROHMANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-499', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-476', 'nama' => 'Mezza luna', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-476', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-473', 'nama' => 'Farida puspitasari', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-473', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-474', 'nama' => 'ANA AZZARINDE MU\'DZIROH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-474', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-492', 'nama' => 'Amelia putri', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-492', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-489', 'nama' => 'Yesika dewi lestari', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-489', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-496', 'nama' => 'Helmi rahmandhika', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-496', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-500', 'nama' => 'Hendrian', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-500', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-495', 'nama' => 'M galuh sudariyanto', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-495', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-497', 'nama' => 'Faiz naufal muafa', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-497', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-490', 'nama' => 'MOH ALDHY FIRMANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-490', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-472', 'nama' => 'ANGGUN SASMITA PUSPA P', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-472', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-506', 'nama' => 'TIA MAGFIROH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-506', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-504', 'nama' => 'DWI PUTRI KUSNI WATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-504', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-502', 'nama' => 'RISQI AMALIA ROHMAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-502', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-503', 'nama' => 'DEVI IDKHA ARTICHA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-503', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-501', 'nama' => 'MALIA IZATUL ROHMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-501', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-514', 'nama' => 'AHMAD NUR FITRIANTO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-514', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-509', 'nama' => 'FAUZI RAHMATULLOH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-509', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-521', 'nama' => 'MUJAHIDAH SHOFINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-521', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-519', 'nama' => 'NUFIYA ALFA ARIDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-519', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-520', 'nama' => 'NAGITA YUANANDA ISTALFATAN N', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-520', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-517', 'nama' => 'M IRFAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-517', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-518', 'nama' => 'ASROFIL WAHYUDI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-518', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-515', 'nama' => 'RIFFO ARMANDO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-515', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-524', 'nama' => 'INDRA DWI LUKMANTORO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-524', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-526', 'nama' => 'MUTIARA TSANIA SALSABILA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-526', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-032', 'nama' => 'FAIS RAFLY DWI N', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-032', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-543', 'nama' => 'NAZILA PUTRI AULIYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-543', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-541', 'nama' => 'INDRI AIDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-541', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-542', 'nama' => 'DIVA PUTRI ARIYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-542', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-549', 'nama' => 'REFINO RAMADHANI CANDRA W', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-549', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-553', 'nama' => 'MOH ALIMUN KHAKIM', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-553', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-554', 'nama' => 'RADIT DWI SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-554', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-556', 'nama' => 'DAVA DWI HENDRAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-556', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-454', 'nama' => 'EMY', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-454', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-537', 'nama' => 'DIAN PANDU SUSILO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-537', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-564', 'nama' => 'RIZU CANDRA WAHYU ARDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-564', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-565', 'nama' => 'HERU TRIO PRASETYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-565', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-574', 'nama' => 'ETY SRI UTAMI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-574', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-538', 'nama' => 'ANDIKA BRIYAN MAULANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-538', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-573', 'nama' => 'DESI TRI LESTARI HARYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-573', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-336', 'nama' => 'ACHMAD ZACKY AWALUDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-336', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-598', 'nama' => 'TATIK YULIATIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-598', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-605', 'nama' => 'Sumali', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-605', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-579', 'nama' => 'FARAH LISA NADIYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-579', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-582', 'nama' => 'EKA LISTIANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-582', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-613', 'nama' => 'MUHAMAD ILHAM DWI CAHYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-613', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-616', 'nama' => 'AHMAD NAUFAL AKMALLUDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-616', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-620', 'nama' => 'SARUL GUNAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-620', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-630', 'nama' => 'LUNA AULIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-630', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-626', 'nama' => 'SHERLEY NUR FADHILAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-626', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-629', 'nama' => 'SITI AISYAH AHMAD', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-629', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-638', 'nama' => 'ACHMAD FAJAR QOMARUZZAMAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-638', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-637', 'nama' => 'ZULIANA SAFITRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-637', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-646', 'nama' => 'HENIK PURWANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-646', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-617', 'nama' => 'TZUFAH ALLAWIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-617', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-635', 'nama' => 'AZIZAHTUL RAMADHANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-635', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-673', 'nama' => 'M. ABDUL LATIF', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-673', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-671', 'nama' => 'ANDIKA RISKI APRILIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-671', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-665', 'nama' => 'ANDIKA DWI SETIAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-665', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-684', 'nama' => 'AZIZ ROZAKI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-684', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-688', 'nama' => 'KRISNA ADJI FAWAJIDAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-688', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-623', 'nama' => 'NUR AZIZAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-623', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-687', 'nama' => 'Feni ambarwati', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-687', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-662', 'nama' => 'LINGGA RACHMATIKA R', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-662', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-705', 'nama' => 'EVI NOVITASARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-705', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-702', 'nama' => 'ACHMAD ENGGAR FIRDZAUS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-702', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-697', 'nama' => 'YAN DEFIT A\'AN SYAIFULLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-697', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-714', 'nama' => 'ISPURWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-714', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-717', 'nama' => 'M NUR AINUN WACHID', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-717', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-527', 'nama' => 'VARIZA IMANDA HERLAMBANG', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-527', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-675', 'nama' => 'AZIZAH ADIYA YULIYA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-675', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-739', 'nama' => 'SRI WAHYUNI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-739', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-740', 'nama' => 'ANIK ERNAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-740', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-758', 'nama' => 'JENNYFER BHAREND', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-758', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-781', 'nama' => 'Sukarni', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-781', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-782', 'nama' => 'Arik Rohmatul Hidayah', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-782', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-783', 'nama' => 'SELVI ELYANA OKTAVIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-783', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-802', 'nama' => 'Jumroh je', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-802', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-794', 'nama' => 'M RENO ARDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-794', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-793', 'nama' => 'MOHAMMAT ADI SATRIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-793', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-763', 'nama' => 'FIRANA WAHYU FEBRIYANTI DEWI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-763', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-778', 'nama' => 'DIMAS ARDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-778', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-822', 'nama' => 'NICO THOMAS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-822', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-779', 'nama' => 'M ZIDNI NUROH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-779', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-811', 'nama' => 'RINA RAHAYU ROMADONA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-811', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-796', 'nama' => 'FERY HARIANTO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-796', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-812', 'nama' => 'RAYSYAH MUKAROMAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-812', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-807', 'nama' => 'NADIAH DEWI L', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-807', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-795', 'nama' => 'RISKA AMELLIA ZAELANTY', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-795', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-817', 'nama' => 'NIZAR ABDI SURYA WIHARTA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-817', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-784', 'nama' => 'LUSI MELINDA RAHMATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-784', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-803', 'nama' => 'DYAH ESTI KURNIAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-803', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-002', 'nama' => 'REVALDI FIRMANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-002', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-306', 'nama' => 'DEVITA NUR ISMAIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-306', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-297', 'nama' => 'MOCHAMAD ABDUL WAKID', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-297', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-835', 'nama' => 'INKA TITUS NABILA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-835', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-825', 'nama' => 'MAULLIDAH DWIYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-825', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-827', 'nama' => 'NURI MAULIDINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-827', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-826', 'nama' => 'MEILA DWI ANGGRAINI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-826', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-836', 'nama' => 'NIKMATUS SHOLIKA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-836', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-832', 'nama' => 'SURUR ROBBANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-832', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-842', 'nama' => 'PUTRI FATMASARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-842', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-743', 'nama' => 'EKA RAHAYU WULANDARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-743', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-851', 'nama' => 'Bagus Setyono', 'bagian' => 'Security', 'barcode_value' => 'LMG-2025-851', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-860', 'nama' => 'AINUR FAIZ ZAKY AMINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-860', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2025-857', 'nama' => 'AMANDA LARASSATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2025-857', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-870', 'nama' => 'M FAHRI AWALUDDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-870', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-874', 'nama' => 'CINTHYA CLAUDHYA S', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-874', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-868', 'nama' => 'AUREL DAMAYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-868', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-867', 'nama' => 'SALSABILLA IFTITA HAFISOZ', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-867', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-864', 'nama' => 'SITI FARIKHATU KHOLIDAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-864', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-875', 'nama' => 'MUHAMMAD HIKAM NAJA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-875', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-886', 'nama' => 'INEZ ANJELLA ELYANA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-886', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-885', 'nama' => 'LULUK NUR QOMARIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-885', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-883', 'nama' => 'NUR AFIFAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-883', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-884', 'nama' => 'INTAN PERMATA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-884', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-882', 'nama' => 'SASKIA NURLINDA MIFTAKHUL JANNAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-882', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-894', 'nama' => 'LAILA NAJWATUS SYAIF', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-894', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-895', 'nama' => 'DECHA FAUZE PRAMADYTHA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-895', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-896', 'nama' => 'ULFATUS SA\'IDAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-896', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-897', 'nama' => 'SITI MARIYA ULFA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-897', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-889', 'nama' => 'SANTI APRILIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-889', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-900', 'nama' => 'ZALINDA MAULIDA PUTRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-900', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-902', 'nama' => 'SHINTA MAYANG SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-902', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-903', 'nama' => 'RELIF MAGHFIROH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-903', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-908', 'nama' => 'ANGGI DEWI WULANDARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-908', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-904', 'nama' => 'WULANDARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-904', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-909', 'nama' => 'NURLINDAH AYU FERLISIAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-909', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-912', 'nama' => 'AHMAD FAIRUS IKHWAN MA\'RUFI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-912', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-918', 'nama' => 'ILHAM SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-918', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-919', 'nama' => 'SYAHRAZAD ANGGARA FAZRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-919', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-926', 'nama' => 'AFRIZAL ANANDA PUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-926', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-929', 'nama' => 'MOH. SYARIF HIDAYATULLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-929', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-931', 'nama' => 'DANI RAHMAN SHOLIHUDDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-931', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-932', 'nama' => 'AIDA NURUL FATIHAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-932', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-935', 'nama' => 'RADIKA DWI SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-935', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-936', 'nama' => 'AYU KHOFIFA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-936', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-944', 'nama' => 'FAHRIZAL RAMADHANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-944', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-945', 'nama' => 'AFIF KHOIRUDDIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-945', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-947', 'nama' => 'Rizki Sumantri', 'bagian' => 'SECURITY', 'barcode_value' => 'LMG-2026-947', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-949', 'nama' => 'Wahyu Tri Afriyan', 'bagian' => 'SECURITY', 'barcode_value' => 'LMG-2026-949', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-950', 'nama' => 'PERMONO OKKY', 'bagian' => 'DRIVER', 'barcode_value' => 'LMG-2026-950', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-952', 'nama' => 'Ratna Nurjanah', 'bagian' => 'OPERATOR', 'barcode_value' => 'LMG-2026-952', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-954', 'nama' => 'Mega Putri Lestari', 'bagian' => 'OPERATOR', 'barcode_value' => 'LMG-2026-954', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-957', 'nama' => 'Muhammad Munir', 'bagian' => 'OPERATOR', 'barcode_value' => 'LMG-2026-957', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-958', 'nama' => 'Zacky Febian Kusuma', 'bagian' => 'OPERATOR', 'barcode_value' => 'LMG-2026-958', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-962', 'nama' => 'Indah Ika Dwi Yulianti', 'bagian' => 'OPERATOR', 'barcode_value' => 'LMG-2026-962', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-964', 'nama' => 'FITRAH MAULANA ALIF KRISNANDA', 'bagian' => 'Security', 'barcode_value' => 'LMG-2026-964', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-965', 'nama' => 'DIMAS HERMAWAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-965', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-966', 'nama' => 'NIA NUR OCTAVIA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-966', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-970', 'nama' => 'NURUL MUIZ', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-970', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-972', 'nama' => 'LIA WAHYU NINGTYAS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-972', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-974', 'nama' => 'MOCH. KUSRONI WIJAYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-974', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-975', 'nama' => 'LULUK MUSDZALIFAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-975', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-976', 'nama' => 'M. ZIDDAN NURDIANYSAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-976', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-977', 'nama' => 'Muhammad Rafi Aziz', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-977', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-978', 'nama' => 'MOCH. FERRI ARDIANSYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-978', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-980', 'nama' => 'IHSAN TEGAR PRAYOGA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-980', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-981', 'nama' => 'RETNO AYU ANGGRAENI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-981', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-982', 'nama' => 'YENIS SEFTIA FITRI RAMADHANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-982', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-983', 'nama' => 'WAHYU EKA ZAHROTUS SITA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-983', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-984', 'nama' => 'WHINA KARTIKA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-984', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-985', 'nama' => 'SHUFI PUTRI RUSDIYANTI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-985', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-986', 'nama' => 'VELISA FITRI AYU AYU HARIANK', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-986', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-987', 'nama' => 'DESI ANGGARA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-987', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-988', 'nama' => 'KUKUH APRILIA PUTRI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-988', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-989', 'nama' => 'KHUMAYRA AGUSTINA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-989', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-990', 'nama' => 'SOFIAN WIBAWAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-990', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-991', 'nama' => 'HENI NAFISAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-991', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-992', 'nama' => 'RISKA AULIA SOLKHATIN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-992', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-993', 'nama' => 'SITI MARIFATUL KHOIRIYAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-993', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-994', 'nama' => 'INDAH ZULFIYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-994', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-995', 'nama' => 'DIANA EKA SETIAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-995', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-996', 'nama' => 'KHOLIFA AYU NATASYA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-996', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-997', 'nama' => 'LABIB NASIRUDIN', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2026-997', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1003', 'nama' => 'AURA VALINCO PRATAMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1003', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-998', 'nama' => 'M RENO PRATAMA PUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-998', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-999', 'nama' => 'ZUDA DWI SAPUTRA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-999', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1002', 'nama' => 'RASYIFA\' FAJWA RAHMATULLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1002', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1004', 'nama' => 'ABD. ROUF KHOIRI', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2026-1004', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1005', 'nama' => 'THARIQ', 'bagian' => 'Ass. Superintenden', 'barcode_value' => 'LMG-2026-1005', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1006', 'nama' => 'YOGI AJI FIRNANDA', 'bagian' => 'Maintenance', 'barcode_value' => 'LMG-2026-1006', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1010', 'nama' => 'HESTI FIRMA NINGTYAS', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1010', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1007', 'nama' => 'SOVIA ANASTASIA MAHARANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1007', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1008', 'nama' => 'SEPTY ARTIKASARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1008', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1009', 'nama' => 'LILIS MA\'RIFAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1009', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1012', 'nama' => 'AMELIA DWI RAMADHANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1012', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1013', 'nama' => 'NABILA LUTHFIANUR FADILLAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1013', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1014', 'nama' => 'YULIATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1014', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1015', 'nama' => 'PURI RETNO WULAN', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1015', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1016', 'nama' => 'AFIFAH AULIA AZ-ZAHRAH', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1016', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1017', 'nama' => 'FEBRIANA NOVITA SARI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1017', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1018', 'nama' => 'KELPIN DIAS PRATAMA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1018', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1011', 'nama' => 'BAGAS PRASTIYO', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1011', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1019', 'nama' => 'DESI FIA NUR ANGGREENI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1019', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1020', 'nama' => 'EKA FATMAWATI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1020', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1022', 'nama' => 'ARUM KUSUMA WARDANI', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1022', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1021', 'nama' => 'ANANDA DESI AYU ABIDA', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1021', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1023', 'nama' => 'Jokocahyono', 'bagian' => 'Operator', 'barcode_value' => 'LMG-2026-1023', 'created_at' => $now, 'updated_at' => $now],
            ['nip' => 'LMG-2026-1024', 'nama' => 'ALIF ARYA FEBRIANTI', 'bagian' => 'Sanitasi', 'barcode_value' => 'LMG-2026-1024', 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach (array_chunk($data, 200) as $chunk) {
            DB::table('karyawan')->upsert($chunk, ['nip'], ['nama', 'bagian', 'barcode_value', 'updated_at']);
        }
    }
}